services:
  n8n:
    build: .
    ports:
      - 5678:5678
    restart: always
    environment:
      - N8N_LOG_LEVEL=debug
      - N8N_METRICS=true

  blog_ingest:
    build: ./blog_ingest
    ports:
      - 8000:8000
    restart: unless-stopped
    env_file:
      - .env
